# Generated by Django 4.2.7 on 2023-11-02 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GO_Shoes',
            fields=[
                ('shoesID', models.AutoField(primary_key=True, serialize=False)),
                ('shoes_image_path', models.TextField()),
                ('shoes_name', models.TextField()),
                ('shoes_description', models.TextField()),
                ('shoes_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shoes_color', models.CharField(max_length=10)),
                ('shoes_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'go_shoes',
                'managed': False,
            },
        ),
    ]
