<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GO_Shoes',
            fields=[
                ('shoesID', models.AutoField(primary_key=True, serialize=False)),
                ('shoes_image_path', models.TextField()),
                ('shoes_name', models.TextField()),
                ('shoes_description', models.TextField()),
                ('shoes_price', models.FloatField()),
                ('shoes_color', models.CharField(max_length=10)),
                ('shoes_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'go_shoes',
                'managed': False,
            },
        ),
    ]
=======
# Generated by Django 4.2.7 on 2023-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GO_Shoes',
            fields=[
                ('shoesID', models.AutoField(primary_key=True, serialize=False)),
                ('shoes_image_path', models.TextField()),
                ('shoes_name', models.TextField()),
                ('shoes_description', models.TextField()),
                ('shoes_price', models.FloatField()),
                ('shoes_color', models.CharField(max_length=10)),
                ('shoes_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'go_shoes',
                'managed': False,
            },
        ),
    ]
>>>>>>> 0d41086a3a90370f94e40901e573e9ddf10d20c3
